### ISSUE TITLE
Share links don't always work

### ISSUE THREAD

**Issue by sixten** [heisch/gloomhaven-item-db#30]
I've been playing through Frosthaven with two other people, and using this excellent tool to share the state of our item availability. One thing that we've noticed, though, is that when I send them new links each week after updating things with new items, those link don't consistently enable the new stuff for them. They are prompted to update their spoiler configuration, but nothing happens.

Here are some of the links in question:

WORKS: https://heisch.github.io/gloomhaven-item-db/#eyJnaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJnaCJdfSwiam90bCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJqb3RsIl19LCJmaCI6eyJjcmFmdHNtYW5CdWlsZGluZ0xldmVsIjp7ImNtIjoyLCJ0cCI6LTEsImp3IjotMSwiZW4iOi0xfSwiaXRlbSI6WzE2OCw5MiwxMDEwLDExMDUsMTEwOSwxMDI1LDExMTYsMTA3Miw4Nyw4OSwxODgsNzYsNTcsNzEsODQsODYsNTYsMjMzLDMxLDg1LDc3LDE4N10sInNwZWNpYWxVbmxvY2tzIjpbXSwiaXRlbXNPd25lZEJ5Ijp7fSwiaW5jbHVkZUdhbWVzIjpbImZoIl19LCJsb2NrU3BvaWxlclBhbmVsIjpmYWxzZX0=

DOESN'T: https://heisch.github.io/gloomhaven-item-db/#eyJmaCI6eyJpdGVtIjpbMTY4LDkyLDEwMTAsMTEwNSwxMTA5LDEwMjUsMTExNiwxMDcyLDg3LDg5LDE4OCw3Niw1Nyw3MSw4NCw4Niw1NiwyMzMsMzEsODUsNzcsMTg3LDU1LDE3OV19LCJsb2NrU3BvaWxlclBhbmVsIjpmYWxzZX0=

DOESN'T: https://heisch.github.io/gloomhaven-item-db/#eyJmaCI6eyJpdGVtIjpbMTY4LDkyLDEwMTAsMTEwNSwxMTA5LDEwMjUsMTExNiwxMDcyLDg3LDg5LDE4OCw3Niw1Nyw3MSw4NCw4Niw1NiwyMzMsMzEsODUsNzcsMTg3LDU1LDE3OSw5MSw5OF19LCJsb2NrU3BvaWxlclBhbmVsIjpmYWxzZX0=

Decoding the data from the fragment identifier, the overall structure of the JSON looks similar, but obviously the working link has a lot more stuff in it.

After a little bit of fiddling around, removing chunks of the information from the working link, encoding that JSON, and trying it, it seems like _maybe_ the trigger is whether or not the top-level `gh` key is present or not? I'm afraid I'm not much of a TypeScript dev, so that may be the best I can do to help diagnose the issue.

**Comment by solomojb** [comment]
Ooh... good catch. I think i know what the issues is.... let me investigate a little.

**Comment by solomojb** [comment]
I found the issue, resolved it and this should be fixed. 

I have been working on a new sharing mode. If you go to  https://heisch.github.io/gloomhaven-item-db/?sharing=true you can experiment with a new form of sharing. (Via an account where you don't need to give a new url each time) I would love feedback on it. 

You need to log in either via google. or email then you share with a different link. Only you need to log in, the people you share with do not have to sign in.

**Comment by skahunter** [comment]
Hey Solomojb!
I love the new sharing mode! Only thing that doesn't seem to work is Store Stock Management. Are you planning to support this via the new account sharing as well?

**Comment by solomojb** [comment]
That's odd, I have never seen that not working before. Can you share your link and I can look at it later? (It's probably a simple bug)

**Comment by skahunter** [comment]
https://heisch.github.io/gloomhaven-item-db/?importFrom=AAtiix3cBogZJyHNYERDIlfTN8U2&lastGame=fh this is the key for the account, and the other key; https://heisch.github.io/gloomhaven-item-db/?lastGame=fh#eyJnaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zT3duZWRCeSI6eyIxIjpbIkNTNyJdLCI0IjpbIkNTNyJdLCIxMCI6WyJDUzciXSwiMTIiOlsiQ1M3Il0sIjQxIjpbIkNTNyJdfSwiaW5jbHVkZUdhbWVzIjpbImdoIiwiZmgiXSwiaXRlbU1hbmFnZW1lbnRUeXBlIjoiTm9uZSIsImNsYXNzZXNJblVzZSI6W10sIml0ZW0iOlsyNzQsMjY4LDIyMiwxODAsMjYzLDE4NiwxNzEsMTg0LDE2NSwxNjYsMTY3LDE3NCwxODksMjIzLDIyNiwyNjEsMjcwLDI2OSwyMDIsMTk0LDE3MywyNjQsMjUxLDI1LDEwNSwxMDldLCJhbGwiOmZhbHNlLCJkaXNwbGF5QXMiOiJsaXN0IiwicHJvc3Blcml0eSI6MSwiaXRlbXNJblVzZUNvdW50Ijp7fX0sImpvdGwiOnsic3BlY2lhbFVubG9ja3MiOltdLCJpdGVtc093bmVkQnkiOnt9LCJpbmNsdWRlR2FtZXMiOlsiam90bCJdLCJpdGVtc0luVXNlQ291bnQiOnt9fSwiZmgiOnsic3BlY2lhbFVubG9ja3MiOltdLCJpdGVtc093bmVkQnkiOnsiMiI6WyJGSDMiXSwiMyI6WyJGSDMiLCJGSDEiXSwiNTUiOlsiRkgxIl0sIjU2IjpbIkZIMSJdLCI4NCI6WyJGSDEzIl0sIjg4IjpbIkZIMyJdLCI5OCI6WyJGSDEiXSwiMTIxIjpbIkZIMTMiXSwiMTI0IjpbIkZIMyIsIkZIMSJdLCIxMjciOlsiRkgxIl0sIjEyOCI6WyJGSDMiLCJGSDEzIl0sIjIzMyI6WyJGSDEiXX0sImluY2x1ZGVHYW1lcyI6WyJmaCJdLCJpdGVtc0luVXNlQ291bnQiOnt9LCJpdGVtTWFuYWdlbWVudFR5cGUiOiJQYXJ0eSIsImNsYXNzZXNJblVzZSI6WyJGSDEiLCJGSDMiLCJGSDEzIiwiRkgxNyJdLCJpdGVtIjpbNTUsOTIsODQsNTQsMjMzLDU2LDU4LDcxLDgzLDk4LDYzLDY5LDg4LDYwLDk2LDIyMV0sImRpc3BsYXlBcyI6ImltYWdlcyIsImNyYWZ0c21hbkJ1aWxkaW5nTGV2ZWwiOnsiY20iOjMsInRwIjotMSwianciOi0xLCJlbiI6LTF9fSwibG9ja1Nwb2lsZXJQYW5lbCI6ZmFsc2V9

**Comment by skahunter** [comment]
Tried multiple different ways still can't get this to work unfortunately

**Comment by solomojb** [comment]
It must be a bug in the logic.  I haven’t had a chance to look at it yet.  

there was a bug that I had fixed where if you didn’t have gloomhaven data nothing would be imported.  Maybe there’s a similar bug with this. 

Do you have any data for gloomhaven by chance? (If not try adding that and see if it works?)

**Comment by solomojb** [comment]
One other question: the old method (sharing the hash) works fine?

**Comment by skahunter** [comment]
Yes that works perfect! (But it requires me to share a new link to the guys every week so I was super happy with seeing your improvement plans!)

**Comment by solomojb** [comment]
Yeah that’s why I created the sharing. My group got tired of having to update the link. 

I’ll try to take a look soon.

**Comment by benknoble** [comment]
I'm having some sharing link issues, not sure if they are related.

Some example configuration (screenshot):

<img width="1393" alt="Frosthaven Spoiler Configuration" src="https://github.com/heisch/gloomhaven-item-db/assets/22802209/2b399bef-5ba2-4e49-839c-6c779b48dc3e">

The sharing link JSON:
```
{
  "gh": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "gh"
    ]
  },
  "jotl": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "jotl"
    ]
  },
  "fh": {
    "item": [
      31,
      60,
      62,
      65,
      71,
      76,
      77,
      83,
      84,
      85,
      86,
      87,
      88,
      90,
      91,
      92,
      93,
      98,
      95,
      1025,
      1072,
      1105,
      1116,
      242,
      186,
      184,
      181,
      172,
      1010,
      188,
      1109,
      233,
      96,
      1037,
      1094,
      1093,
      1021,
      1053,
      1106,
      1115,
      243,
      221,
      176,
      64,
      66
    ],
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "fh",
      "gh",
      "fhss"
    ],
    "soloClass": [
      "FH2"
    ]
  },
  "lockSpoilerPanel": false
}
```

The resulting configuration (screenshot):

<img width="1393" alt="Wrong Frosthaven Spoiler Configuration" src="https://github.com/heisch/gloomhaven-item-db/assets/22802209/40ce95ac-baeb-43c4-9fa2-7153367809d7">

In particular,
- Craftsman level is reset;
- Trading Post unlock is reset;
- solo items, despite being marked, do not show in the item list;
- I'm sure there's more :)

The "bad" link:
```
https://heisch.github.io/gloomhaven-item-db/?lastGame=fh#eyJnaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJnaCJdfSwiam90bCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJqb3RsIl19LCJmaCI6eyJpdGVtIjpbMzEsNjAsNjIsNjUsNzEsNzYsNzcsODMsODQsODUsODYsODcsODgsOTAsOTEsOTIsOTMsOTgsOTUsMTAyNSwxMDcyLDExMDUsMTExNiwyNDIsMTg2LDE4NCwxODEsMTcyLDEwMTAsMTg4LDExMDksMjMzLDk2LDEwMzcsMTA5NCwxMDkzLDEwMjEsMTA1MywxMTA2LDExMTUsMjQzLDIyMSwxNzYsNjQsNjZdLCJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJmaCIsImdoIiwiZmhzcyJdLCJzb2xvQ2xhc3MiOlsiRkgyIl19LCJsb2NrU3BvaWxlclBhbmVsIjpmYWxzZX0=
```

Here's an older link that mostly works (though is older, so doesn't have all our items):
```
https://heisch.github.io/gloomhaven-item-db/?lastGame=fh#eyJnaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJnaCJdfSwiam90bCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJqb3RsIl19LCJmaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6eyI2IjoyLCI5IjoxLCIxMiI6MSwiMTciOjEsIjI0IjoxLCIzMSI6MSwiODQiOjEsIjg1IjoxLCI4NiI6MSwiOTAiOjEsIjkxIjoxLCIxMjgiOjEsIjE3NiI6MSwiMTg4IjoxLCIyMjEiOjEsIjIzMyI6MSwiMjQzIjoxLCIxMDEwIjoyLCIxMTA5IjoxfSwiaXRlbXNPd25lZEJ5Ijp7fSwiaW5jbHVkZUdhbWVzIjpbImZoIiwiZmhzcyIsImdoIl0sIml0ZW1NYW5hZ2VtZW50VHlwZSI6IlNpbXBsZSIsImNyYWZ0c21hbkJ1aWxkaW5nTGV2ZWwiOnsiY20iOjUsInRwIjoyLCJqdyI6LTEsImVuIjotMX0sIml0ZW0iOlszMSw2MCw2Miw2NSw3MSw3Niw3Nyw4Myw4NCw4NSw4Niw4Nyw4OCw5MCw5MSw5Miw5Myw5OCw5NSwxMDI1LDEwNzIsMTEwNSwxMTE2LDI0MiwxODYsMTg0LDE4MSwxNzIsMTAxMCwxODgsMTEwOSwyMzMsOTYsMTAzNywxMDk0LDEwOTMsMTAyMSwxMDUzLDExMDYsMTExNSwyNDMsMjIxLDE3Nl0sInNvbG9DbGFzcyI6WyJGSDIiXX0sImxvY2tTcG9pbGVyUGFuZWwiOmZhbHNlfQ==
```
and corresponding JSON
```
{
  "gh": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "gh"
    ]
  },
  "jotl": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "jotl"
    ]
  },
  "fh": {
    "specialUnlocks": [],
    "itemsInUseCount": {
      "6": 2,
      "9": 1,
      "12": 1,
      "17": 1,
      "24": 1,
      "31": 1,
      "84": 1,
      "85": 1,
      "86": 1,
      "90": 1,
      "91": 1,
      "128": 1,
      "176": 1,
      "188": 1,
      "221": 1,
      "233": 1,
      "243": 1,
      "1010": 2,
      "1109": 1
    },
    "itemsOwnedBy": {},
    "includeGames": [
      "fh",
      "fhss",
      "gh"
    ],
    "itemManagementType": "Simple",
    "craftsmanBuildingLevel": {
      "cm": 5,
      "tp": 2,
      "jw": -1,
      "en": -1
    },
    "item": [
      31,
      60,
      62,
      65,
      71,
      76,
      77,
      83,
      84,
      85,
      86,
      87,
      88,
      90,
      91,
      92,
      93,
      98,
      95,
      1025,
      1072,
      1105,
      1116,
      242,
      186,
      184,
      181,
      172,
      1010,
      188,
      1109,
      233,
      96,
      1037,
      1094,
      1093,
      1021,
      1053,
      1106,
      1115,
      243,
      221,
      176
    ],
    "soloClass": [
      "FH2"
    ]
  },
  "lockSpoilerPanel": false
}
```

but the solo items still don't show in the item list panel.

**Comment by benknoble** [comment]
I opened a new page and reconfigured spoilers, which got me this link:
```
https://heisch.github.io/gloomhaven-item-db/?lastGame=fh#eyJnaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJnaCJdfSwiam90bCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6e30sIml0ZW1zT3duZWRCeSI6e30sImluY2x1ZGVHYW1lcyI6WyJqb3RsIl19LCJmaCI6eyJzcGVjaWFsVW5sb2NrcyI6W10sIml0ZW1zSW5Vc2VDb3VudCI6eyI2IjoyLCI5IjoxLCIxMiI6MSwiMTciOjEsIjI0IjoxLCIzMSI6MSwiODQiOjEsIjg1IjoxLCI4NiI6MSwiOTAiOjEsIjkxIjoxLCIxMjgiOjEsIjE3NiI6MSwiMTg4IjoxLCIyMjEiOjEsIjIzMyI6MSwiMjQzIjoxLCIxMDEwIjoyLCIxMTA5IjoxfSwiaXRlbXNPd25lZEJ5Ijp7fSwiaW5jbHVkZUdhbWVzIjpbImZoIiwiZmhzcyIsImdoIl0sIml0ZW1NYW5hZ2VtZW50VHlwZSI6IlNpbXBsZSIsImNyYWZ0c21hbkJ1aWxkaW5nTGV2ZWwiOnsiY20iOjUsInRwIjoyLCJqdyI6LTEsImVuIjotMX0sIml0ZW0iOlszMSw2MCw2Miw2NSw3MSw3Niw3Nyw4Myw4NCw4NSw4Niw4Nyw4OCw5MCw5MSw5Miw5Myw5OCw5NSwxMDI1LDEwNzIsMTEwNSwxMTE2LDI0MiwxODYsMTg0LDE4MSwxNzIsMTAxMCwxODgsMTEwOSwyMzMsOTYsMTAzNywxMDk0LDEwOTMsMTAyMSwxMDUzLDExMDYsMTExNSwyNDMsMjIxLDE3Niw2NCw2Nl0sInNvbG9DbGFzcyI6WyJGSDIiXX0sImxvY2tTcG9pbGVyUGFuZWwiOmZhbHNlfQ==
```

JSON:
```
{
  "gh": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "gh"
    ]
  },
  "jotl": {
    "specialUnlocks": [],
    "itemsInUseCount": {},
    "itemsOwnedBy": {},
    "includeGames": [
      "jotl"
    ]
  },
  "fh": {
    "specialUnlocks": [],
    "itemsInUseCount": {
      "6": 2,
      "9": 1,
      "12": 1,
      "17": 1,
      "24": 1,
      "31": 1,
      "84": 1,
      "85": 1,
      "86": 1,
      "90": 1,
      "91": 1,
      "128": 1,
      "176": 1,
      "188": 1,
      "221": 1,
      "233": 1,
      "243": 1,
      "1010": 2,
      "1109": 1
    },
    "itemsOwnedBy": {},
    "includeGames": [
      "fh",
      "fhss",
      "gh"
    ],
    "itemManagementType": "Simple",
    "craftsmanBuildingLevel": {
      "cm": 5,
      "tp": 2,
      "jw": -1,
      "en": -1
    },
    "item": [
      31,
      60,
      62,
      65,
      71,
      76,
      77,
      83,
      84,
      85,
      86,
      87,
      88,
      90,
      91,
      92,
      93,
      98,
      95,
      1025,
      1072,
      1105,
      1116,
      242,
      186,
      184,
      181,
      172,
      1010,
      188,
      1109,
      233,
      96,
      1037,
      1094,
      1093,
      1021,
      1053,
      1106,
      1115,
      243,
      221,
      176,
      64,
      66
    ],
    "soloClass": [
      "FH2"
    ]
  },
  "lockSpoilerPanel": false
}
```

I wrote above that solo items don't show; that may have been true, but in the reconfigured link it appears they do show. (Maybe my page was just stale and I need to reload every so often?)

**Comment by solomojb** [comment]
It's odd that in the first link the Solo Items isn't showing.  From the data FH2 should definitely showing.

As for the buildings unlocked in your first example: 
```
 "craftsmanBuildingLevel": {
      "cm": 5,
      "tp": 2,
      "jw": -1,
      "en": -1
    },
```

Is missing. That should be the logic that is unlocking it.

**Comment by benknoble** [comment]
> It's odd that in the first link the Solo Items isn't showing.  From the data FH2 should definitely showing.
> 
> 
> 
> As for the buildings unlocked in your first example: 
> 
> ```
> 
>  "craftsmanBuildingLevel": {
> 
>       "cm": 5,
> 
>       "tp": 2,
> 
>       "jw": -1,
> 
>       "en": -1
> 
>     },
> 
> ```
> 
> 
> 
> Is missing. That should be the logic that is unlocking it. 

Yeah, I gathered both of those things from staring at the data. Just concerned that the share link is not being appropriately refreshed when editing configuration.

**Comment by solomojb** [comment]
@skahunter I finally am getting around to looking into this.   I don't see any data exported associated with your account.  Did you remember to hit the export button on the share screen?

**Comment by benknoble** [comment]
A few questions…
- I keep seeing references to accounts, but the site for me is the same anonymous "share link" it's been for a while. What am I missing?
- Are you aware that the build and deploy action has been failing for a long time now (something about dependency failures)? It almost looks like you're generating and committing to `gh-pages` by hand ?

**Comment by solomojb** [comment]
@benknoble hey!  I added a sharing mode that can be accessed by sharing=true as a qsp.  I’ve left it behind the flag as I wasn’t sure how well it worked. 

Yeah I tried to get GitHub to do the builds for me but I never turned it off. I am indeed building and committing by hand.  I’ve been meaning to turn that off.

**Comment by benknoble** [comment]
Ah! I'll try it out.

**Comment by solomojb** [comment]
Please do.  I’ve been using it with my group now for a while with no problems.  Let me know if you see any issues.
